# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cf8fb6171336bcc39c28472d25bea0603248df9311d03d8aa34d50b30d225c37b78a54ae395396da368a1076daa326868af6470666d5606b53f0490eefe45f4

test:
  secret_key_base: a737b228deb7ac84154e4b49a9f3f8931d2dd0c8bd0c79b1e2edc8c800f645be1853983dced2e7252930d146bc89ded14f7fc78e258918a3e10b07102e4457f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
